/* Generated by wayland-scanner 1.25.0 */

#ifndef UWM_BAR_UNSTABLE_V1_SERVER_PROTOCOL_H
#define UWM_BAR_UNSTABLE_V1_SERVER_PROTOCOL_H

#include <stdint.h>
#include <stddef.h>
#include "wayland-server.h"

#ifdef  __cplusplus
extern "C" {
#endif

struct wl_client;
struct wl_resource;

/**
 * @page page_uwm_bar_unstable_v1 The uwm_bar_unstable_v1 protocol
 * @section page_ifaces_uwm_bar_unstable_v1 Interfaces
 * - @subpage page_iface_zwp_uwm_bar_v1 - UWM bar manager
 * - @subpage page_iface_zwp_uwm_workspace_group_v1 - workspace group for an output
 * @section page_copyright_uwm_bar_unstable_v1 Copyright
 * <pre>
 *
 * Copyright © 2026 UWM Contributors
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or
 * sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice (including
 * the next paragraph) shall be included in all copies or
 * substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT.  IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 * </pre>
 */
struct wl_output;
struct zwp_uwm_bar_v1;
struct zwp_uwm_workspace_group_v1;

#ifndef ZWP_UWM_BAR_V1_INTERFACE
#define ZWP_UWM_BAR_V1_INTERFACE
/**
 * @page page_iface_zwp_uwm_bar_v1 zwp_uwm_bar_v1
 * @section page_iface_zwp_uwm_bar_v1_desc Description
 *
 * A global interface used by bar clients to receive workspace
 * state and focused window title from the UWM compositor.
 *
 * One instance is created per output to support multi-monitor.
 * @section page_iface_zwp_uwm_bar_v1_api API
 * See @ref iface_zwp_uwm_bar_v1.
 */
/**
 * @defgroup iface_zwp_uwm_bar_v1 The zwp_uwm_bar_v1 interface
 *
 * A global interface used by bar clients to receive workspace
 * state and focused window title from the UWM compositor.
 *
 * One instance is created per output to support multi-monitor.
 */
extern const struct wl_interface zwp_uwm_bar_v1_interface;
#endif
#ifndef ZWP_UWM_WORKSPACE_GROUP_V1_INTERFACE
#define ZWP_UWM_WORKSPACE_GROUP_V1_INTERFACE
/**
 * @page page_iface_zwp_uwm_workspace_group_v1 zwp_uwm_workspace_group_v1
 * @section page_iface_zwp_uwm_workspace_group_v1_desc Description
 *
 * Reports workspace state and focused window title for a
 * specific output. Events are sent in batches terminated
 * by a done event.
 * @section page_iface_zwp_uwm_workspace_group_v1_api API
 * See @ref iface_zwp_uwm_workspace_group_v1.
 */
/**
 * @defgroup iface_zwp_uwm_workspace_group_v1 The zwp_uwm_workspace_group_v1 interface
 *
 * Reports workspace state and focused window title for a
 * specific output. Events are sent in batches terminated
 * by a done event.
 */
extern const struct wl_interface zwp_uwm_workspace_group_v1_interface;
#endif

/**
 * @ingroup iface_zwp_uwm_bar_v1
 * @struct zwp_uwm_bar_v1_interface
 */
struct zwp_uwm_bar_v1_interface {
	/**
	 * get workspace group for an output
	 *
	 * Create a workspace group object for the given output. If
	 * output is NULL, the group covers all workspaces.
	 */
	void (*get_workspace_group)(struct wl_client *client,
				    struct wl_resource *resource,
				    struct wl_resource *output,
				    uint32_t id);
	/**
	 * destroy the bar manager
	 *
	 * 
	 */
	void (*destroy)(struct wl_client *client,
			struct wl_resource *resource);
};


/**
 * @ingroup iface_zwp_uwm_bar_v1
 */
#define ZWP_UWM_BAR_V1_GET_WORKSPACE_GROUP_SINCE_VERSION 1
/**
 * @ingroup iface_zwp_uwm_bar_v1
 */
#define ZWP_UWM_BAR_V1_DESTROY_SINCE_VERSION 1

/**
 * @ingroup iface_zwp_uwm_workspace_group_v1
 * @struct zwp_uwm_workspace_group_v1_interface
 */
struct zwp_uwm_workspace_group_v1_interface {
	/**
	 * destroy the workspace group
	 *
	 * 
	 */
	void (*destroy)(struct wl_client *client,
			struct wl_resource *resource);
};

#define ZWP_UWM_WORKSPACE_GROUP_V1_WORKSPACE 0
#define ZWP_UWM_WORKSPACE_GROUP_V1_FOCUSED_TITLE 1
#define ZWP_UWM_WORKSPACE_GROUP_V1_DONE 2

/**
 * @ingroup iface_zwp_uwm_workspace_group_v1
 */
#define ZWP_UWM_WORKSPACE_GROUP_V1_WORKSPACE_SINCE_VERSION 1
/**
 * @ingroup iface_zwp_uwm_workspace_group_v1
 */
#define ZWP_UWM_WORKSPACE_GROUP_V1_FOCUSED_TITLE_SINCE_VERSION 1
/**
 * @ingroup iface_zwp_uwm_workspace_group_v1
 */
#define ZWP_UWM_WORKSPACE_GROUP_V1_DONE_SINCE_VERSION 1

/**
 * @ingroup iface_zwp_uwm_workspace_group_v1
 */
#define ZWP_UWM_WORKSPACE_GROUP_V1_DESTROY_SINCE_VERSION 1

/**
 * @ingroup iface_zwp_uwm_workspace_group_v1
 * Sends an workspace event to the client owning the resource.
 * @param resource_ The client's resource
 */
static inline void
zwp_uwm_workspace_group_v1_send_workspace(struct wl_resource *resource_, uint32_t id, uint32_t active, uint32_t occupied)
{
	wl_resource_post_event(resource_, ZWP_UWM_WORKSPACE_GROUP_V1_WORKSPACE, id, active, occupied);
}

/**
 * @ingroup iface_zwp_uwm_workspace_group_v1
 * Sends an focused_title event to the client owning the resource.
 * @param resource_ The client's resource
 */
static inline void
zwp_uwm_workspace_group_v1_send_focused_title(struct wl_resource *resource_, const char *title)
{
	wl_resource_post_event(resource_, ZWP_UWM_WORKSPACE_GROUP_V1_FOCUSED_TITLE, title);
}

/**
 * @ingroup iface_zwp_uwm_workspace_group_v1
 * Sends an done event to the client owning the resource.
 * @param resource_ The client's resource
 */
static inline void
zwp_uwm_workspace_group_v1_send_done(struct wl_resource *resource_)
{
	wl_resource_post_event(resource_, ZWP_UWM_WORKSPACE_GROUP_V1_DONE);
}

#ifdef  __cplusplus
}
#endif

#endif
