/* Generated by wayland-scanner 1.25.0 */

#ifndef UWM_BAR_UNSTABLE_V1_CLIENT_PROTOCOL_H
#define UWM_BAR_UNSTABLE_V1_CLIENT_PROTOCOL_H

#include <stdint.h>
#include <stddef.h>
#include "wayland-client.h"

#ifdef  __cplusplus
extern "C" {
#endif

/**
 * @page page_uwm_bar_unstable_v1 The uwm_bar_unstable_v1 protocol
 * @section page_ifaces_uwm_bar_unstable_v1 Interfaces
 * - @subpage page_iface_zwp_uwm_bar_v1 - UWM bar manager
 * - @subpage page_iface_zwp_uwm_workspace_group_v1 - workspace group for an output
 * @section page_copyright_uwm_bar_unstable_v1 Copyright
 * <pre>
 *
 * Copyright © 2026 UWM Contributors
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or
 * sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice (including
 * the next paragraph) shall be included in all copies or
 * substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT.  IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 * </pre>
 */
struct wl_output;
struct zwp_uwm_bar_v1;
struct zwp_uwm_workspace_group_v1;

#ifndef ZWP_UWM_BAR_V1_INTERFACE
#define ZWP_UWM_BAR_V1_INTERFACE
/**
 * @page page_iface_zwp_uwm_bar_v1 zwp_uwm_bar_v1
 * @section page_iface_zwp_uwm_bar_v1_desc Description
 *
 * A global interface used by bar clients to receive workspace
 * state and focused window title from the UWM compositor.
 *
 * One instance is created per output to support multi-monitor.
 * @section page_iface_zwp_uwm_bar_v1_api API
 * See @ref iface_zwp_uwm_bar_v1.
 */
/**
 * @defgroup iface_zwp_uwm_bar_v1 The zwp_uwm_bar_v1 interface
 *
 * A global interface used by bar clients to receive workspace
 * state and focused window title from the UWM compositor.
 *
 * One instance is created per output to support multi-monitor.
 */
extern const struct wl_interface zwp_uwm_bar_v1_interface;
#endif
#ifndef ZWP_UWM_WORKSPACE_GROUP_V1_INTERFACE
#define ZWP_UWM_WORKSPACE_GROUP_V1_INTERFACE
/**
 * @page page_iface_zwp_uwm_workspace_group_v1 zwp_uwm_workspace_group_v1
 * @section page_iface_zwp_uwm_workspace_group_v1_desc Description
 *
 * Reports workspace state and focused window title for a
 * specific output. Events are sent in batches terminated
 * by a done event.
 * @section page_iface_zwp_uwm_workspace_group_v1_api API
 * See @ref iface_zwp_uwm_workspace_group_v1.
 */
/**
 * @defgroup iface_zwp_uwm_workspace_group_v1 The zwp_uwm_workspace_group_v1 interface
 *
 * Reports workspace state and focused window title for a
 * specific output. Events are sent in batches terminated
 * by a done event.
 */
extern const struct wl_interface zwp_uwm_workspace_group_v1_interface;
#endif

#define ZWP_UWM_BAR_V1_GET_WORKSPACE_GROUP 0
#define ZWP_UWM_BAR_V1_DESTROY 1


/**
 * @ingroup iface_zwp_uwm_bar_v1
 */
#define ZWP_UWM_BAR_V1_GET_WORKSPACE_GROUP_SINCE_VERSION 1
/**
 * @ingroup iface_zwp_uwm_bar_v1
 */
#define ZWP_UWM_BAR_V1_DESTROY_SINCE_VERSION 1

/** @ingroup iface_zwp_uwm_bar_v1 */
static inline void
zwp_uwm_bar_v1_set_user_data(struct zwp_uwm_bar_v1 *zwp_uwm_bar_v1, void *user_data)
{
	wl_proxy_set_user_data((struct wl_proxy *) zwp_uwm_bar_v1, user_data);
}

/** @ingroup iface_zwp_uwm_bar_v1 */
static inline void *
zwp_uwm_bar_v1_get_user_data(struct zwp_uwm_bar_v1 *zwp_uwm_bar_v1)
{
	return wl_proxy_get_user_data((struct wl_proxy *) zwp_uwm_bar_v1);
}

static inline uint32_t
zwp_uwm_bar_v1_get_version(struct zwp_uwm_bar_v1 *zwp_uwm_bar_v1)
{
	return wl_proxy_get_version((struct wl_proxy *) zwp_uwm_bar_v1);
}

/**
 * @ingroup iface_zwp_uwm_bar_v1
 *
 * Create a workspace group object for the given output.
 * If output is NULL, the group covers all workspaces.
 */
static inline struct zwp_uwm_workspace_group_v1 *
zwp_uwm_bar_v1_get_workspace_group(struct zwp_uwm_bar_v1 *zwp_uwm_bar_v1, struct wl_output *output)
{
	struct wl_proxy *id;

	id = wl_proxy_marshal_flags((struct wl_proxy *) zwp_uwm_bar_v1,
			 ZWP_UWM_BAR_V1_GET_WORKSPACE_GROUP, &zwp_uwm_workspace_group_v1_interface, wl_proxy_get_version((struct wl_proxy *) zwp_uwm_bar_v1), 0, output, NULL);

	return (struct zwp_uwm_workspace_group_v1 *) id;
}

/**
 * @ingroup iface_zwp_uwm_bar_v1
 */
static inline void
zwp_uwm_bar_v1_destroy(struct zwp_uwm_bar_v1 *zwp_uwm_bar_v1)
{
	wl_proxy_marshal_flags((struct wl_proxy *) zwp_uwm_bar_v1,
			 ZWP_UWM_BAR_V1_DESTROY, NULL, wl_proxy_get_version((struct wl_proxy *) zwp_uwm_bar_v1), WL_MARSHAL_FLAG_DESTROY);
}

/**
 * @ingroup iface_zwp_uwm_workspace_group_v1
 * @struct zwp_uwm_workspace_group_v1_listener
 */
struct zwp_uwm_workspace_group_v1_listener {
	/**
	 * workspace state
	 *
	 * Announces a workspace on this output. Sent at startup and on
	 * changes. The active flag is 1 if this is the current workspace
	 * on the output, 0 otherwise. The occupied flag is 1 if the
	 * workspace has any windows on it.
	 */
	void (*workspace)(void *data,
			  struct zwp_uwm_workspace_group_v1 *zwp_uwm_workspace_group_v1,
			  uint32_t id,
			  uint32_t active,
			  uint32_t occupied);
	/**
	 * focused window title
	 *
	 * The title of the currently focused window on the output
	 * associated with this workspace group.
	 */
	void (*focused_title)(void *data,
			      struct zwp_uwm_workspace_group_v1 *zwp_uwm_workspace_group_v1,
			      const char *title);
	/**
	 * batch complete
	 *
	 * Marks the end of a batch of workspace and title updates. The
	 * client should process all previous events in the batch before
	 * redrawing.
	 */
	void (*done)(void *data,
		     struct zwp_uwm_workspace_group_v1 *zwp_uwm_workspace_group_v1);
};

/**
 * @ingroup iface_zwp_uwm_workspace_group_v1
 */
static inline int
zwp_uwm_workspace_group_v1_add_listener(struct zwp_uwm_workspace_group_v1 *zwp_uwm_workspace_group_v1,
					const struct zwp_uwm_workspace_group_v1_listener *listener, void *data)
{
	return wl_proxy_add_listener((struct wl_proxy *) zwp_uwm_workspace_group_v1,
				     (void (**)(void)) listener, data);
}

#define ZWP_UWM_WORKSPACE_GROUP_V1_DESTROY 0

/**
 * @ingroup iface_zwp_uwm_workspace_group_v1
 */
#define ZWP_UWM_WORKSPACE_GROUP_V1_WORKSPACE_SINCE_VERSION 1
/**
 * @ingroup iface_zwp_uwm_workspace_group_v1
 */
#define ZWP_UWM_WORKSPACE_GROUP_V1_FOCUSED_TITLE_SINCE_VERSION 1
/**
 * @ingroup iface_zwp_uwm_workspace_group_v1
 */
#define ZWP_UWM_WORKSPACE_GROUP_V1_DONE_SINCE_VERSION 1

/**
 * @ingroup iface_zwp_uwm_workspace_group_v1
 */
#define ZWP_UWM_WORKSPACE_GROUP_V1_DESTROY_SINCE_VERSION 1

/** @ingroup iface_zwp_uwm_workspace_group_v1 */
static inline void
zwp_uwm_workspace_group_v1_set_user_data(struct zwp_uwm_workspace_group_v1 *zwp_uwm_workspace_group_v1, void *user_data)
{
	wl_proxy_set_user_data((struct wl_proxy *) zwp_uwm_workspace_group_v1, user_data);
}

/** @ingroup iface_zwp_uwm_workspace_group_v1 */
static inline void *
zwp_uwm_workspace_group_v1_get_user_data(struct zwp_uwm_workspace_group_v1 *zwp_uwm_workspace_group_v1)
{
	return wl_proxy_get_user_data((struct wl_proxy *) zwp_uwm_workspace_group_v1);
}

static inline uint32_t
zwp_uwm_workspace_group_v1_get_version(struct zwp_uwm_workspace_group_v1 *zwp_uwm_workspace_group_v1)
{
	return wl_proxy_get_version((struct wl_proxy *) zwp_uwm_workspace_group_v1);
}

/**
 * @ingroup iface_zwp_uwm_workspace_group_v1
 */
static inline void
zwp_uwm_workspace_group_v1_destroy(struct zwp_uwm_workspace_group_v1 *zwp_uwm_workspace_group_v1)
{
	wl_proxy_marshal_flags((struct wl_proxy *) zwp_uwm_workspace_group_v1,
			 ZWP_UWM_WORKSPACE_GROUP_V1_DESTROY, NULL, wl_proxy_get_version((struct wl_proxy *) zwp_uwm_workspace_group_v1), WL_MARSHAL_FLAG_DESTROY);
}

#ifdef  __cplusplus
}
#endif

#endif
